controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # coxa_leg_controller:
    #   type: forward_command_controller/ForwardCommandController
    # femur_leg_controller:
    #   type: forward_command_controller/ForwardCommandController
    tibia_leg_controller:
      type: forward_command_controller/ForwardCommandController

# coxa_leg_controller:
#   ros__parameters:
#     joints:
#       - coxa_base_1
#     interface_name: position

# femur_leg_controller:
#   ros__parameters:
#     joints:
#       - femur_base_1
#     interface_name: position

tibia_leg_controller:
  ros__parameters:
    joints:
      - tibia_base_1
    interface_name: position
