<?xml version='1.0' encoding='utf-8'?>

<robot name="Hexapod" xmlns:xacro="https://www.ros.org/wiki/xacro">

    <xacro:include filename="controller.xacro" />

    <xacro:property name="servo_length" value="0.075"/><!-- 75mm taken cause 82mm was too outside of the base-->
    
    <xacro:property name="box_length" value="0.01"/>

    <xacro:property name="coxa_length" value="0.040"/>
    <xacro:property name="leg_radius" value="0.005"/>

    <xacro:property name="femur_length" value="0.1166"/>
    <xacro:property name="tibia_length" value="0.13"/>

    <xacro:property name="servo_mass" value="0.070"/>
    <xacro:property name="coxa_mass" value="0.05"/>
    <xacro:property name="femur_mass" value="0.1"/>
    <xacro:property name="tibia_mass" value="0.1"/>

    <link name="base_link">
        <inertial>
            <origin xyz="2.3553741432180777e-07 2.224092921723409e-05 0.003026303676307155" rpy="0.0 0.0 0.0" />
            <mass value="0.7689223035628137" />
            <inertia ixx="0.0010390137355587251" iyy="0.0010400150822437112" izz="0.0020742729104693478" ixy="2.966445125900137e-10" iyz="4.4983354420999026e-10" ixz="-2.2246256263541832e-10" />
        </inertial>
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0" />
            <geometry>
                 <!-- file:///$(find arm_03)/description/meshes/armA/armA_0.stl
                package://hexapod_rviz/meshes/Body.stl  -->
                <mesh filename="file:///$(find hexapod)/models/hexagon.stl" scale="0.001 0.001 0.001" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0" />
            <geometry>
                <mesh filename="file:///$(find hexapod)/models/hexagon.stl" scale="0.001 0.001 0.001" />
            </geometry>
        </collision>
    </link>

    <xacro:macro name="base_servo" params="suffix d1 d2 ang f">
        <link name="servo1_${suffix}">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${box_length} ${box_length} ${box_length}"/>
                </geometry>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${box_length} ${box_length} ${box_length}"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0 0 0" rpy="0.0 0.0 0.0" />
                <mass value="${servo_mass}" />
                <inertia ixx="${servo_mass*(2*box_length*box_length)/12}" iyy="${servo_mass*(2*box_length*box_length)/12}" izz="${servo_mass*(2*box_length*box_length)/12}" ixy="0" iyz="0" ixz="0" />
            </inertial>
        </link>

        <joint name="servo_base_${suffix}" type="fixed">
            <parent link="base_link"/>
            <child link="servo1_${suffix}"/>
            <origin xyz="${servo_length*d1} ${servo_length*d2} 0.01" rpy="1.57 0 ${pi*ang}"/>
        </joint>

    </xacro:macro>
  
    <xacro:macro name="coxa_joint" params="suffix d1 d2 ang f">
        
        <link name="coxa_${suffix}">
            <visual>
                <origin xyz="0 0 -${coxa_length/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${leg_radius}" length="${coxa_length}"/>
                </geometry>
                <material name="coxa_colour_${suffix}">
                    <color rgba="0.3 0.3 0.3 1.0"/>
                </material>
            </visual>

            <collision>
                <origin xyz="0 0 -${coxa_length/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${leg_radius}" length="${coxa_length}"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0 0 -${coxa_length/2}" rpy="0 0 0" />
                <mass value="${coxa_mass}"/>
                <inertia ixx="${coxa_mass*((3*leg_radius*leg_radius)+(coxa_length*coxa_length))/12}" iyy="${coxa_mass*((3*leg_radius*leg_radius)+(coxa_length*coxa_length))/12}" izz="${coxa_mass*(leg_radius*leg_radius)/2}" ixy="0" ixz="0" iyz="0"/>
            </inertial>
        </link>
        
        <joint name="coxa_base_${suffix}" type="revolute">

            <parent link="servo1_${suffix}"/>
            <child link="coxa_${suffix}"/>
            <!-- <origin xyz="${servo_length*d1} ${servo_length*d2} ${leg_radius*2}" rpy="1.57 ${pi * f} ${pi*ang}"/> -->
            <origin xyz="0.0 0.0 -${box_length/2}" rpy="0 0.0 0.0"/>
            <axis xyz="0 ${-f} 0"/>
            <limit lower="-${pi/4}" upper="${pi/4}" effort="100.0" velocity="100.0"/>

        </joint>

    </xacro:macro>

    <xacro:macro name="femur_coxa_servo" params="suffix">
        <link name="coxa_servo_${suffix}">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="${box_length/2}"/>
                </geometry>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="${box_length/2}"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0 0 0" rpy="0.0 0.0 0.0" />
                <mass value="${femur_mass}"/>
                <inertia ixx="${2*femur_mass*(box_length*box_length)/5}" iyy="${2*femur_mass*(box_length*box_length)/5}" izz="${2*femur_mass*(box_length*box_length)/5}" ixy="0" ixz="0" iyz="0"/>
            </inertial>
        </link>

        <joint name="coxa_servo_${suffix}" type="fixed">
            <parent link="coxa_${suffix}"/>
            <child link="coxa_servo_${suffix}"/>
            <origin xyz="0 0 -${coxa_length+(box_length/2)}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="femur_joint" params="suffix d1 d2 ang f">
        
        <link name="femur_${suffix}">
            <visual>
                <origin xyz="0 0 -${femur_length/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${leg_radius}" length="${femur_length}"/>
                </geometry>
                <material name="femur_colour_${suffix}">
                    <color rgba="0.3 0.3 0.3 1.0"/>
                </material>
            </visual>

            <collision>
                <origin xyz="0 0 -${femur_length/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${leg_radius}" length="${femur_length}"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0 0 -${femur_length/2}" rpy="0 0 0" />
                <mass value="${femur_mass}"/>
                <inertia ixx="${femur_mass*((3*leg_radius*leg_radius)+(femur_length*femur_length))/12}" iyy="${femur_mass*((3*leg_radius*leg_radius)+(femur_length*femur_length))/12}" izz="${femur_mass*(leg_radius*leg_radius)/2}" ixy="0" ixz="0" iyz="0"/>
            </inertial>
        </link>
        
        <joint name="femur_base_${suffix}" type="revolute">

            <parent link="coxa_servo_${suffix}"/>
            <child link="femur_${suffix}"/>
            <origin xyz="0.0 0.0 -${box_length/2}" rpy="0.0 0.0 0.0"/>
            <axis xyz="${-f} 0 0"/>
            <limit lower="-${pi/2}" upper="${pi/1.5}" effort="100.0" velocity="100.0"/>

        </joint>

    </xacro:macro>

    <xacro:macro name="tibia_femur_servo" params="suffix">
        <link name="femur_servo_${suffix}">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="${box_length/2}"/>
                </geometry>
            </visual>

            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="${box_length/2}"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0 0 0" rpy="0.0 0.0 0.0" />
                <mass value="${femur_mass}"/>
                <inertia ixx="${2*femur_mass*(box_length*box_length)/5}" iyy="${2*femur_mass*(box_length*box_length)/5}" izz="${2*femur_mass*(box_length*box_length)/5}" ixy="0" ixz="0" iyz="0"/>
            </inertial>
        </link>

        <joint name="femur_servo_${suffix}" type="fixed">
        
            <parent link="femur_${suffix}"/>
            <child link="femur_servo_${suffix}"/>
            <origin xyz="0 0 -${femur_length+(box_length/2)}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="tibia_joint" params="suffix d1 d2 ang f">
        
        <link name="tibia_${suffix}">
            <visual>
                <origin xyz="0 0 -${tibia_length/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${leg_radius}" length="${tibia_length}"/>
                </geometry>
                <material name="tibia_colour_${suffix}">
                    <color rgba="0.3 0.3 0.3 1.0"/>
                </material>
            </visual>

            <collision>
                <origin xyz="0 0 -${tibia_length/2}" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="${leg_radius}" length="${tibia_length}"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0 0 -${tibia_length/2}" rpy="0 0 0" />
                <mass value="${tibia_mass}"/>
                <inertia ixx="${tibia_mass*((3*leg_radius*leg_radius)+(tibia_length*tibia_length))/12}" iyy="${tibia_mass*((3*leg_radius*leg_radius)+(tibia_length*tibia_length))/12}" izz="${tibia_mass*(leg_radius*leg_radius)/2}" ixy="0" ixz="0" iyz="0"/>
            </inertial>            
        </link>
        
        <joint name="tibia_base_${suffix}" type="revolute">

            <parent link="femur_servo_${suffix}"/>
            <child link="tibia_${suffix}"/>
            <origin xyz="0.0 0.0 -${box_length/2}" rpy="0 0.0 0.0"/>
            <axis xyz="${-f} 0 0"/>
            <limit lower="-${pi/2}" upper="${pi/1.5}" effort="100.0" velocity="100.0"/>

        </joint>

    </xacro:macro>

    <xacro:macro name="leg" params="suffix d1 d2 ang f">
        <xacro:base_servo suffix="${suffix}" d1="${d1}" d2="${d2}" ang="${ang}" f="${f}"/>
        <xacro:coxa_joint suffix="${suffix}" d1="${d1}" d2="${d2}" ang="${ang}" f="${f}"/>
        <xacro:femur_coxa_servo suffix="${suffix}"/>
        <xacro:femur_joint suffix="${suffix}" d1="${d1}" d2="${d2}" ang="${ang}" f="${f}"/>
        <xacro:tibia_femur_servo suffix="${suffix}"/>
        <xacro:tibia_joint suffix="${suffix}" d1="${d1}" d2="${d2}" ang="${ang}" f="${f}"/>
    </xacro:macro>

    
    <xacro:leg suffix="1" d1="0" d2="1" ang="$(eval 0)" f="1"/>
    <!-- <xacro:leg suffix="2" d1="-0.8661580944" d2="0.4997701026" ang="$(eval 1/3)" f="1"/>
    <xacro:leg suffix="3" d1="0.8661580944" d2="0.4997701026" ang="$(eval -1/3)" f="1"/>
    <xacro:leg suffix="4" d1="-0.8661580944" d2="-0.4997701026" ang="$(eval 2/3)" f="1"/>
    <xacro:leg suffix="5" d1="0.8661580944" d2="-0.4997701026" ang="$(eval -2/3)" f="1"/>
    <xacro:leg suffix="6" d1="0" d2="-1" ang="$(eval -1)" f="1"/> -->
</robot>